config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :posts
  resources :comments, only:[:new, :destroy]
  resources :home
  resources :sessions

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  

  root 'sessions#new'

  delete '/comments/:id' => "comments#destroy", as: :delete_comment

  delete '/posts/:id' => "posts#destroy", as: :delete_post

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

 helper_method :current_user

  def current_user
  	if session[:user_id]
    @current_user = User.find(session[:user_id])
   end
    
  end
  protect_from_forgery with: :exception

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @post = @comment.post
    @comment.save
      redirect_to post_path(@post) 
  end

   def destroy
    Comment.find(comment_params).destroy
   redirect_to post_path(@post)
   	
  end

  def update 
    @comment = Comment.find(comment_params)
    @post=@comment.post
    @comment.update(comment_params)
    if @comment.save
      flash[:notice] = "Comment updated"
    else 
      flash[:alert] = "Error in updating"
    end 
    redirect_to post_path(@post)
  end 


  private

  def comment_params
    params.require(:comment).permit(:body, :user_id, :post_id)
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
    	flash[:notice] = "post created"
       redirect_to posts_path
      else
        flash[:alert] = "error"
      end
  end

  def show
    if current_user == nil
      redirect_to root_path
    else
      @post = Post.find(params[:id])
      @user = @post.user
      @comment = @post.comments
    end
  end

  def update
    @post = Post.find(params[:id])
    @post = Post.update(post_params)
    flash[:notice] = "Post updated"  
    redirect_to post_path
  end

  def edit
  	@post = Post.find(params[:id])
  end

  def destroy
    @comments = Post.find(params[:id]).comments
    Post.find(params[:id]).destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:body, :user_id)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
  	@user = User.where(email: params[:email]).first
      if @user && @user.password ==  params[:password]
        session[:user_id] = @user.id
        flash[:notice] = "You have been signed in"
        redirect_to posts_path
      else 
        flash[:alert] = "This email and password combination does not match"
        redirect_to root_path
      end
  end
	
	def destroy
		session.clear
		redirect_to root_path
		flash[:notice] = "You have been signed out"
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
      if @user.save
       flash[:notice] = "You account is created"
       redirect_to users_path
      else
        flash[:alert] = "error"
        redirect_to new_user_path
    end

  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    @post = Post.new
    @comments = Comment.all
    @comment = Comment.new
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    flash[:notice] = "User has been updated"
    redirect_to user_path
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    User.find(params[:id]).destroy
      redirect_to users_path
    end

  private

  def user_params
    params.require(:user).permit(:fname, :lname, :email, :username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<%= form_for @comment do |f| %>
	<%= f.label :body %>
	<%= f.text_field :body %>
	<%= f.submit :create %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Much blah about nothing</title>
  <link href='https://fonts.googleapis.com/css?family=Luckiest+Guy' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
	<h1>MUCH BLAH ABOUT NOTHING</h1>
</header>
  <%= flash[:notice] if flash[:notice] %> 
	<%= flash[:alert] if flash[:alert] %>
  <nav>
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Users", users_path %></li>
			<li><%= link_to "Posts", posts_path %></li>
		</ul>
	</nav>


<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<div id="edit-post">
  <h2>Edit Post</h2>
  <%= form_for @post do |f| %><br>
	<%= f.label :post %><br>
	<%= f.text_area :body %><br>
	<%= f.submit "edit post"%><br>
<% end %>
<br>
<br>
<%= link_to "Edit", edit_post_path(@post) %>
<%= button_to "Delete", post_path(@posts), method: :delete %>

</div>

app/views/posts/index.html.erb
<div id="post-all">
  <h1> All Posts </h1>
    <p><% @posts.each do |p| %></p>
    <p><%= link_to p.user.username, users_path %></p>
    <p><%= link_to "Post", post_path(p.id) %></p>  
  <% end %>
</div>

app/views/posts/show.html.erb
<p><%= link_to("User", user_path(@user.id)) %></p>

<p><%= @post.user.username %></p>

<h2><p id= "my-post"> My Posts </p></h2>
  <%= @post.body %>


  <%if @post.user_id == current_user.id%>
    <%= link_to("Delete", post_path(@post), method: :delete) %>
	  <%= link_to("Edit", edit_post_path, method: :get) %>
  <% end %>

<% if false %>
  <%= form_for ([@post,@comment]) do |f| %>
	  <%=f.text_field :body %>
	  <%=f.hidden_field :user_id, value: session[:user_id] %>
	  <%=f.hidden_field :post_id, value: @post.id %>
	  <%=f.submit "Add Comment"%>
  <% end %>
<% end %>
	

<h2><p id="p-comments">Comments</p></p>	
<% @post.comments.each do |x| %>
  <p><%= x.user.username %></p>
  <p><%= x.body %></p>
  <%if @post.user_id == current_user.id || x.user.id == current_user.id%>
		<%= button_to "Delete comment", post_comment_path(@post.id, x.id), method: :delete %>
	<% end %>
<% end %>

app/views/users/edit.html.erb
<h2>Edit profile</h2>

<p><%= form_for @user do |f| %></p>

  <%= f.label :fname, "First name" %><br>
  <%= f.text_field :fname %><br>

  <%= f.label :lname, "Last name" %><br>
  <%= f.text_field :lname %><br>

  <%= f.label :email, "email" %><br>
  <%= f.text_field :email %><br>

  <%= f.label :username, "username" %><br>
  <%= f.text_field :username %><br>

  <%= f.label :password, "Password" %><br>
  <%= f.text_field :password %><br>

  <%= f.submit %><br>

<% end %>

app/views/users/index.html.erb
<div id = "userlist"
  <% @users.each do |user| %>

	<%= link_to user.username, user_path(user.id) %>
	</br>

<% end %>

</div>

app/views/users/new.html.erb
<p><%= form_for User.new do |f| %></p>

  <%= f.label :fname, "First name" %><br>
  <%= f.text_field :fname %><br>

  <%= f.label :lname, "Last name" %><br>
  <%= f.text_field :lname %><br>

  <%= f.label :email, "email" %><br>
  <%= f.text_field :email %><br>

  <%= f.label :username, "username" %><br>
  <%= f.text_field :username %><br>

  <%= f.label :password, "Password" %><br>
  <%= f.text_field :password %><br>

  <%= f.submit %><br>

<% end %>
<%= link_to("Back", users_path)%>

app/views/users/show.html.erb
<div id="userw">
<h2>Welcome <%= @user.username.capitalize %></h2>
<p><%= @user.email %></p>
<p><%= @user.username %></p>
</div>

<div id ="cd">
<h3><%= link_to("Delete Profile", user_path(@user), method: :delete) %></h3>
<h3><%= link_to "Edit Profile", edit_user_path(@user) %></h3>
<br>
</div>


<div id = "postd">
  <h3>Add your Post</h3>
 
    <%= form_for @post do |f| %>
	    <%= f.label :post %>
	    <%= f.text_area :body %>
	    <%=f.hidden_field :user_id, value: session[:user_id] %>
	    <%= f.submit %>
	
  <% end %>
</div>

<% @posts.each do |p| %>
	<%= link_to("Post", post_path(p.id)) %>
	<p><%= p.body %></p>
<% end %>

<p><%= form_tag("/logout", method: "delete") do %></p>
	<p><%= submit_tag("Logout") %></p>
<% end %>
</div>